### ISSUE TITLE
DockerfileUI entrypoint script "worker_online.py" is missing

### ISSUE THREAD

**Issue by pintaric** [f1tenth/f1tenth_gym#1]
**Problem description:**

The entrypoint script `worker_online.py` (referenced in `DockerfileUI`) is missing.

**Steps to reproduce:**

```
docker build -t f1tenth_gym_ui -f DockerfileUI .
xhost local:$USER
docker run --gpus all -it --name=f1tenth_gym_ui_container --rm -p 5557:5557 -p 5558:5558 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix f1tenth_gym_ui
```

**Output:**

`python3: can't open file 'worker_online.py': [Errno 2] No such file or directory`

**Comment by hzheng40** [comment]
Thanks for bringing this up. We're working on migrating the repo and some of the documentation is out of date.

**Comment by hzheng40** [comment]
Experimentation branch now on exp_py.
Removed out of date Dockerfiles.
