### ISSUE TITLE
Vec env init takes a long time

### ISSUE THREAD

**Issue by hzheng40** [f1tenth/f1tenth_gym#106]
Not sure why this is happening, but when initializing vec envs it takes way longer:

```bash
python3 -m timeit -n 1 -v "import gymnasium as gym; gym.make('f110_gym:f110-v0')" 
raw times: 4.96 sec, 4.5 sec, 4.98 sec, 4.93 sec, 4.89 sec

python3 -m timeit -n 1 -v "import gymnasium as gym; [gym.make('f110_gym:f110-v0') for _ in range(10)]" 
raw times: 48.2 sec, 44 sec, 45.1 sec, 44.9 sec, 46 sec

python3 -m timeit -n 1 -v "import gymnasium as gym; gym.make_vec('f110_gym:f110-v0', num_envs=10)" 
raw times: 378 sec, 384 sec, 376 sec, 409 sec, 417 sec
```

I think the expectation is that it should scale linearly with the number of envs.

**Comment by luigiberducci** [comment]
Hi @hzheng40, it seems related to the vectorization mode, by default "async" in gymnasium 0.29.1.
It suggests that the current version of the gym does not work well with multiprocessing.

However, it is not related to the use of vectorized environments. If you specify vectorization mode as "synch", you obtain same performance. 

```
python3 -m timeit -n 1 -v "import gymnasium as gym; [gym.make('f110_gym:f110-v0') for _ in range(10)]"
raw times: 40.3 sec, 36.4 sec, 45.2 sec, 45 sec, 42 sec

python3 -m timeit -n 1 -v "import gymnasium as gym; gym.make_vec('f110_gym:f110-v0', num_envs=10, vectorization_mode='sync')"
raw times: 37.4 sec, 35.8 sec, 36.7 sec, 41.3 sec, 40.6 sec
```

**Comment by luigiberducci** [comment]
Closing this for now as not stricly related to the vector API.
