### ISSUE TITLE
v1.0.0 Waypoint follow example results in frequent crashes

### ISSUE THREAD

**Issue by nandantumu** [f1tenth/f1tenth_gym#109]
**Describe the bug**
The root cause of this behavior is that the reset function does not provide the opportunity to choose the raceline on the track that is used for restarts. The PurePursuit controller overcorrects, and this results in a crash.

**To Reproduce**
1. Run the waypoint follow example

**Expected behavior**
The waypoint follow should not result in a crash

**Additional context**
Adding an additional option to set the line along which a respawn happens would fix this issue. This is inside `masked_reset.py`

**Comment by nandantumu** [comment]
Alternative solution is to make the planner follow the centerline instead of the raceline

**Comment by luigiberducci** [comment]
Yes, the reset samples points around the centerline. However, most of the controllers (observed this in pp and mpc) crash when starting far from the raceline.

I would simply modify the default reset to use the raceline. Even if I believe the problem is on the controller side.

**Comment by luigiberducci** [comment]
> @luigiberducci @nandantumu Is there an open source implementation of a MPC controller for the f1tenth-gym environment or one that can be incorporated with moderate effort? If yes, could you point me to one? Thanks.

Hi, you might want to have a look at [f1tenth_planning](https://github.com/f1tenth/f1tenth_planning). If you have other questions, please open an issue there.
