### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by tungkaG** [f1tenth/f1tenth_gym#122]
**Describe the bug**
I got this error while running pip install -e .
![Screenshot from 2024-03-14 22-18-33](https://github.com/f1tenth/f1tenth_gym/assets/148013249/e39964fb-55e2-44f3-b454-cb9810a6f8a8)

**To Reproduce**
run the following commands:
virtualenv gym_env
source gym_env/bin/activate
git clone https://github.com/f1tenth/f1tenth_gym.git
cd f1tenth_gym
pip install -e .

**Expected behavior**
every packages should be installed properly and no error messages

**Desktop (please complete the following information):**
 - OS: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Additional context**
I read a past issue that describes the same problem, i tried the solutions given yet i still could not solve this

**Comment by Mineinjava** [comment]
> Hi, I know this is closed, but according to [this thread](https://answers.ros.org/question/396439/setuptoolsdeprecationwarning-setuppy-install-is-deprecated-use-build-and-pip-and-other-standards-based-tools/), do make sure you install `pip3 install setuptools==58.2.0` if you are in Ubuntu 22.04 + ROS Humble. If not, the rest of your ROS workspace will not build!
> 
> This is because the installation method for Python has changed.

running `pip3 install setuptools==58.2.0` worked for me
