### ISSUE TITLE
random_trackgen.py not working

### ISSUE THREAD

**Issue by GarryGao00** [f1tenth/f1tenth_gym#126]
**Describe the bug**
when running the code using the example prompt, there is an error: 

```
$python3 random_trackgen.py --seed 12345 --num_maps 1
Track generation: 1224..1543 -> 319-tiles track
Traceback (most recent call last):
  File "random_trackgen.py", line 234, in <module>
    convert_track(track, track_int, track_ext, i)
  File "random_trackgen.py", line 180, in convert_track
    ax.plot(*track_int.T, color='black', linewidth=3)
TypeError: iteration over a 0-d array
```

**Expected behavior**
The new map.png and map.yaml should be generated into ./maps folder

**Desktop (please complete the following information):**
 - OS: 22.04.1-Ubuntu 
- Python: Python 3.8.19
- f110-gym: 0.2.1
- gym: 0.19.0

**Potential Solution**

I create a pull request that seems to fix the problem.

**Comment by luigiberducci** [comment]
Hi @GarryGao00, 
Looking at your information, I think you are working on the main branch. Is it correct?

If so, the `random_trackgen` has been already fixed for the next major release.
You can find it in the branch `v1.0.0`.

**Comment by luigiberducci** [comment]
Closing for now.
