### ISSUE TITLE
Installed docker container but libraries not installed

### ISSUE THREAD

**Issue by astrosaeed** [f1tenth/f1tenth_gym#16]
Hello,

This shouldn't be a bug from your end.
I followed the README documentation and ran the docker scripts. However, it seems that, inside the container environment, no libraries are installed including gym, numpy, and even Python. 

I don't have much experience with Docker but it's not clear what I am missing. Would be happy to know if anyone else had the same issue

**Comment by hzheng40** [comment]
Hi,
Did the docker image finish building successfully? The README at its current stage is a little out-dated, I want to see if it's the Dockerfile itself needs to be fixed.

**Comment by astrosaeed** [comment]
I believe it did, I do not remember seeing any errors. But let me build it one more time and will let you know.

**Comment by astrosaeed** [comment]
I tried again, there were a few warnings but no error during building.  
![Screenshot from 2020-10-05 09-13-27](https://user-images.githubusercontent.com/32550602/95084048-577fb300-06eb-11eb-9d91-a1672b1f2e13.png)

**Comment by hzheng40** [comment]
Only python3 is included in the container, maybe that's why?

**Comment by astrosaeed** [comment]
You are right. I thought just typing Python would execute Python3 as well. It is importing the libraries successfully.
