### ISSUE TITLE
How to reset environment state?

### ISSUE THREAD

**Issue by sisaha9** [f1tenth/f1tenth_gym#17]
Whenever I launch the demo now it is already collided. I may have clicked save by mistake but I redownloaded the gym_bridge.rviz here and uploaded it and it still did not work

**Comment by hzheng40** [comment]
You'll have to make a call to the reset function. [https://github.com/f1tenth/f1tenth_gym#example-usage](https://github.com/f1tenth/f1tenth_gym#example-usage).
Also, you mentioned rviz, which is only used in ROS, maybe [https://github.com/f1tenth/f1tenth_gym_ros](https://github.com/f1tenth/f1tenth_gym_ros) is the repo that you're looking for?

**Comment by sisaha9** [comment]
Oh you are right. Thanks!
