### ISSUE TITLE
Lap time accuracy

### ISSUE THREAD

**Issue by ayoubraji** [f1tenth/f1tenth_gym#2]
**Bug description**
As already privately signaled to the developers, it happens sometimes that the car goes really close to the boundaries and so it triggers the checkpoint used by the lap time system which is in reality in the opposite part of the track.

For example, sometimes it gives me 12s and other times 20s depending on how close the car goes to the boundaries.

**To Reproduce**
Watch the [videos](https://drive.google.com/drive/folders/1GLBD9wEn2exMV1H5t2MMHprCem1YZaeb?usp=sharing).

**Expected behavior**
As already have been told me correcting the starting lane width can fix the problem but I think it should be used a more accurate solution. At least for the future.

**Suggested solution**
Consider using the projection of the car position in a reference path, so using a spline and check whenever the car passes a certain s position on the spline. We use this system in our simulators and in the real f1tenth car, it seems accurate.

To do it in python:

1. [PythonRobotics cubic_spline_planner](https://github.com/AtsushiSakai/PythonRobotics/blob/77f6277e9c86e3b20a74eabfe9be6da3ba339308/PathPlanning/CubicSpline/cubic_spline_planner.py)
2. before starting, create the spline for a reference trajectory:
` path = Spline2D(xs, ys)`
3. at each iteration, update actual pose on the path:
```
 path.update_current_s(car_pose)
```
and then check if it passed a s_reference:
`if path.cur_s > s_reference:`

Of course this should be done for each car, so having two path variables but if you use the calc_s function maybe you can use a unique path variable and check the projection of each car using path.calc_s(x,y). In this way it should be faster.

For any further detail don't hesitate to contact me. If you want I can even create a fork of the sim and make the changes and then let you know how it goes.

**Comment by ayoubraji** [comment]
The quick fix for the race I assume is correct the right_t and left_t [here ](https://github.com/f1tenth/f1tenth_gym/blob/fbfc11e9ef0b9cfa58cb9536af6e0267e38778a6/gym/f110_gym/envs/f110_env.py#L238)to make it adapt for the race track

**Comment by ayoubraji** [comment]
Using left_t = 2 and right_t = 2 fixes the problem and now it seems accurate!

**Comment by hzheng40** [comment]
Temporarily fixed by #3 .
