### ISSUE TITLE
Idea: add random obstacle to track 

### ISSUE THREAD

**Issue by BDEvan5** [f1tenth/f1tenth_gym#22]
The ROS simulator has a great feature of being able to easily add and remove random obstacles on the track.
I think this feature would be very useful in this simulator too, namely to test benchmark 2 which is a track with random obstacles.

**Comment by hzheng40** [comment]
The current GUI lacks the buttons and associated callback functions provided by RViz. It'll require some work into modifying the GUI in pyglet and creating clean callback functions to update the map. We'll add this to the list of potential features to be added.
Currently, if you want to add obstacles, you can add them to the map image file.

**Comment by BDEvan5** [comment]
I made a pull request which allows you to add obstacles to the track.
It doesn't have buttons yet, but can be used with the .add-obstacles() method
