### ISSUE TITLE
Simulator throw a division by zero error from check_ttc_jit()

### ISSUE THREAD

**Issue by qtweng** [f1tenth/f1tenth_gym#30]
**Describe the bug**
The simulation sometimes throws a division by zero error seemingly stemming from some values being passed into the parameter cosines that causes the collision check to have a division by zero

**Screenshots**
![image](https://user-images.githubusercontent.com/47102225/132752171-a62d9089-049e-404c-8a26-be9fe026a256.png)

**Comment by hzheng40** [comment]
Can you describe how one can replicate this issue? Was it with a specific map/pose of the agents?

**Comment by qtweng** [comment]
Hi, I've actually encountered this issue when using the environment that has been modified to support deep reinforcement learning. I have only changed the main script and the gym environment from the original. https://github.com/qtweng/f1tenth-gym
Running the main.py in the above repo will do this.

**Comment by hzheng40** [comment]
There's no main.py in the repo.

**Comment by qtweng** [comment]
Sorry, I meant the main.py in the pkg/src/pkg like usual.

**Comment by qtweng** [comment]
Actually, I think I've found my issue. This happened because I did an improper operation on a python list on my part. This check is fine if the list is valid. I apologize for the false alert. Thanks

**Comment by qtweng** [comment]
Seems I was too hasty. I did not fix the error with the fix on my side.

**Comment by hzheng40** [comment]
Does this happen on other maps?

**Comment by hzheng40** [comment]
Also, you have significantly changed the code from either riders or us, so it'll be really hard for me to help you debug. Could you also try to run something with the map you're testing using the recommended way shown in the example of this repo? That way it'll be easier for me to tell if it was an existing bug or a new introduced bug.

**Comment by qtweng** [comment]
I appears to only happen on the new competition map. I will try running it on the original version of the repo.

**Comment by qtweng** [comment]
Appears to be an unrelated Pytorch calculation error that throws an exception in a weird place.
