### ISSUE TITLE
Model reference point is different when switching

### ISSUE THREAD

**Issue by atomyks** [f1tenth/f1tenth_gym#51]
The reference point for `vehicle_dynamics_st()` and `vehicle_dynamics_ks()` is not the same so switching between them is not correct. Instead of using `vehicle_dynamics_ks()` we can use `vehicle_dynamics_cog` ([here](https://gitlab.lrz.de/tum-cps/commonroad-vehicle-models/-/blob/master/PYTHON/vehiclemodels/utils/vehicle_dynamics_ks_cog.py)) which will solve the problem.

**Comment by hzheng40** [comment]
Resolved by #86
