### ISSUE TITLE
refactoring of track ingestion

### ISSUE THREAD

**Issue by luigiberducci** [f1tenth/f1tenth_gym#77]
1. restructure map dir with subfolders, e.g. `maps/<racetrack_name>/`
2. create `racetrack` object containing occupancy, centerline and raceline (if available) to avoid the user to load cvs files for the planner
3. simplify the env creation by passing only the `map_name`, without `map_path` and `map_ext`
4. automatic download racetracks from [`f1tenth_racetracks`](https://github.com/f1tenth/f1tenth_racetracks/)

**Comment by luigiberducci** [comment]
Branch `dev_track_refactoring` implements steps 1, 2, 3.
For the integration of `f1tenth_racetracks`, see issue [https://github.com/f1tenth/f1tenth_racetracks/issues/3](https://github.com/f1tenth/f1tenth_racetracks/issues/3)

**Comment by luigiberducci** [comment]
Ready to open PR.

@hzheng40 could you please check [f1tenth/f1tenth_racetracks#3](https://github.com/f1tenth/f1tenth_racetracks/issues/3) to decide how to proceed?

Questions:
- The available maps do not have racelines (vegas, skirk, etc.), shall we keep them or provide a set of tracks+racelines?
- Shall we integrate the racetracks as in point 4?

**Comment by hzheng40** [comment]
Resolved by #82
