### ISSUE TITLE
Unify track assets (old ones don't have raceline)

### ISSUE THREAD

**Issue by hzheng40** [f1tenth/f1tenth_gym#85]
However, we should decide if keeping the old tracks (without raceline and centerline) or get rid of them.

_Originally posted by @luigiberducci in https://github.com/f1tenth/f1tenth_gym/issues/82#issuecomment-1631464417_

**Comment by luigiberducci** [comment]
Cannot remove Skirk, Berlin because used in the scan test.

@hzheng40 is it possible to generate the legacy scans files for a few of the new tracks to get rid of the old ones?

**Comment by luigiberducci** [comment]
TO DO:
- Test the current simulator on the old maps for a last time, then remove the old tracks
- Modify the script to generate the legacy scan to run with the new simulator on the new maps
- Update the test to use the new maps

**Comment by hzheng40** [comment]
Fixed by #103
