### ISSUE TITLE
Reset doesn't work with VectorEnv api: https://gymnasium.farama.org/api/vector/

### ISSUE THREAD

**Issue by hzheng40** [f1tenth/f1tenth_gym#93]
Reset by pose doesn't work with VectorEnv API, should consider setting initial pose as an argument during make().

**Comment by luigiberducci** [comment]
Can you provide an example? 

I can reset the vectorized environment through the options. See tests in the linked pr.

**Comment by hzheng40** [comment]
I was using the instantiation used in CleanRL: [here](https://github.com/vwxyzjn/cleanrl/blob/2d660b6d3053ea9037c746b4c9f3a6faa1f20c44/cleanrl/ppo_continuous_action.py#L172C23-L172C36), where multiple envs can run in parallel.

**Comment by luigiberducci** [comment]
Good idea, we can define reset modes like in racecar_gym (random, grid, etc) and pass them in the config

**Comment by hzheng40** [comment]
Fixed by #94
