### ISSUE TITLE
Use namedtuples for agent observations, instead of Dict

### ISSUE THREAD

**Issue by nandantumu** [f1tenth/f1tenth_gym#96]
This would be so casting it to a tensor or vector is much easier, and does not require the user to dig through source to identify what the keys in the observation are.

**Comment by axelbr** [comment]
Hi nandan!
i think that the farama apis do not support namedtuples with their spaces (which are kind of a documentation of what to expect).
furthermore, i guess it would make it more difficult to use wrappers that modify the observation space, no?
